services:
  pg-upload-server:
    image: bitnami/postgresql:latest
    ports:
      - '5423:5423'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
